In [4]:
import jsonlines

with jsonlines.open('../data/prompts/taxonomy_phase2_gemini-3-flash-preview.jsonl') as reader:
    for obj in reader:
        print(obj)

{'discipline': 'Attention Mechanism Theory', 'subfield': 'Transformers and Large-scale Architectures', 'field': 'Representation Learning and Deep Learning', 'subjects': [{'name': 'Mathematical Foundations of Kernel-based Attention', 'level': 'Foundational', 'description': 'Exploration of self-attention as a kernel operator and its grounding in functional analysis and Hilbert spaces.', 'key_subtopics': ['Softmax as a Kernel Integral Operator', 'Reproducing Kernel Hilbert Space (RKHS) Embeddings', 'Lipschitz Continuity and Stability of Self-Attention', 'Universal Approximation Theorems for Transformers', 'Fixed-Point Theory in Multi-Head Attention Maps', 'The Role of Normalization (LayerNorm/RMSNorm) in Gradient Flow']}, {'name': 'Approximation Theory and Low-Rank Efficient Attention', 'level': 'Advanced', 'description': 'Techniques for reducing the quadratic complexity of dot-product attention through mathematical approximations.', 'key_subtopics': ['Nyström Method for Low-Rank Matrix Approximation', 'Positive Orthogonal Random Features (FAVOR+)', 'Kernel Linearization and Linformer Theory', 'Locality-Sensitive Hashing (LSH) and Reformer Architectures', 'Error Bounds of Sparse vs. Dense Attention Matrices', 'Fast Fourier Transform (FFT) based Token Mixing']}, {'name': 'Hardware-Aware Attention and Memory Hierarchy Optimization', 'level': 'Advanced', 'description': 'System-level implementation of attention mechanisms focusing on IO-awareness and GPU kernel optimization.', 'key_subtopics': ['FlashAttention: Tiling and Recomputation Strategies', 'Online Softmax Normalization for Streaming Sequences', 'Block-Sparse Attention Kernels and Triton Programming', 'Quantization-Aware Training (QAT) for Attention Weights', 'Memory-Efficient Backpropagation (Gradients of Attention)', 'PagedAttention and Key-Value (KV) Cache Management']}, {'name': 'Associative Memory and Modern Hopfield Networks', 'level': 'Advanced', 'description': 'The theoretical bridge between attention mechanisms and biological/computational associative memory models.', 'key_subtopics': ['Modern Hopfield Networks (MHN) with Continuous States', 'Energy-Based Interpretation of Self-Attention', 'Dense Associative Memories (DAM) and Pattern Retrieval', 'Fixed-Point Dynamics and Error Correction in Transformers', 'Relationship between Attention Heads and Memory Slots']}, {'name': 'Geometric Deep Learning and Equivariant Attention', 'level': 'Frontier', 'description': 'Extending attention to non-Euclidean spaces and ensuring symmetry invariance in physical and structural modeling.', 'key_subtopics': ['SO(3) and SE(3) Equivariant Transformers', 'Graph Attention Networks (GAT) and Message Passing Dualities', 'Gauge Equivariant Attention on Manifolds', 'Invariant Feature Learning in 3D Point Clouds', 'Clifford Algebra Attention for Geometric Algebra', 'Equivariant Attention for Protein Folding and Molecular Dynamics']}, {'name': 'State Space Models and Linear Recurrence Dualities', 'level': 'Frontier', 'description': 'Investigation of the intersection between classical State Space Models (SSMs) and modern deep learning recurrence.', 'key_subtopics': ['Structured State Space Sequence Models (S4)', 'HiPPO (High-order Polynomial Projection Operators)', 'Recurrent-Convolutional Duality and Parallelization', 'Associative Scan Algorithms for Linear Recurrence', 'Selective State Spaces and Hardware-Aware Gating (Mamba)', 'Discretization Schemes (Bilinear, Zero-Order Hold)']}, {'name': 'Mechanistic Interpretability of Attention Circuits', 'level': 'Frontier', 'description': 'Reverse-engineering the internal representations and logic gates formed by attention heads during training.', 'key_subtopics': ['Induction Heads and In-Context Learning Mechanisms', 'Residual Stream Decomposition and Virtual Weights', 'Polysemanticity and Superposition in Attention Patterns', 'Logit Lens and Attribution Patching', 'Circuit Analysis of Mathematical Reasoning in Transformers', 'Singular Learning Theory (SLT) of Phase Transitions']}, {'name': 'Optimization Dynamics and Scaling Laws in Attention', 'level': 'Frontier', 'description': 'Theoretical analysis of how attention-based models scale with compute, data, and parameters.', 'key_subtopics': ['Neural Tangent Kernel (NTK) for Transformer Architectures', 'Chinchilla Scaling Laws and Compute-Optimal Frontiers', 'Grokking and Out-of-Distribution Generalization Dynamics', 'Weight Initialization Schemes (Fixup, ReZero, T-Fixup)', 'Curvature Analysis of the Transformer Loss Landscape', 'Spectral Convergence of Attention Weights during Training']}], 'status': 'success'}
{'discipline': 'Weather and Climate Prediction with ML', 'subfield': 'AI for Climate, Environment, and Earth Sciences', 'field': 'AI for Science, Engineering, and Discovery', 'subjects': [{'name': 'Differentiable Data Assimilation and Neural Kalman Filters', 'level': 'Foundational', 'description': 'Integration of classical state estimation with differentiable programming to learn observation operators and model error terms.', 'key_subtopics': ['Variational Data Assimilation (4D-Var) as Recurrent Neural Networks', 'Ensemble Kalman Filter (EnKF) with Learned Localization', 'Differentiable Physics-Based Forward Operators', 'End-to-End Learning of State Estimators', 'Bias Correction and Model-Error Modeling', 'Backpropagation through Numerical Solvers']}, {'name': 'Geometric Deep Learning on Spherical Manifolds', 'level': 'Advanced', 'description': "Exploration of deep learning architectures tailored for the Earth's spherical geometry and non-Euclidean grids.", 'key_subtopics': ['Spherical Harmonics and S2CNNs', 'Graph Neural Networks (GNNs) on Icosahedral Grids', 'Equivariant CNNs for Global Symmetry Preservation', 'MeshGraphNets for Lagrangian Fluid Simulation', 'Hierarchical Multi-scale Graph Representations', 'Rotational Invariance in Atmospheric Motion']}, {'name': 'Neural Operators for Infinite-Dimensional PDE Mapping', 'level': 'Advanced', 'description': 'Study of operators that learn mappings between function spaces, enabling resolution-invariant weather prediction.', 'key_subtopics': ['Fourier Neural Operators (FNO) for Fluid Dynamics', 'Deep Operator Networks (DeepONet) and Branch-Trunk Architectures', 'Spectral Convolutions and Aliasing Effects', 'Kernel Integral Operators and Attention Mechanisms', 'Zero-shot Super-resolution for Meteorological Fields', 'Adaptive Fourier Neural Operators (AFNO) for Global Forecasting']}, {'name': 'Probabilistic Generative Modeling for Ensemble Prediction', 'level': 'Advanced', 'description': 'Advanced methods for quantifying uncertainty and generating high-resolution realizations from low-resolution climate data.', 'key_subtopics': ['Diffusion Probabilistic Models for Stochastic Downscaling', 'Score-matching for Density Estimation of Weather States', 'Conditional Generative Adversarial Networks (cGANs) for Rainfall Synthesis', 'Normalizing Flows for Multi-modal Posterior Distributions', 'Variational Autoencoders (VAEs) for Latent Climate Manifolds', 'Continuous Ranked Probability Score (CRPS) Optimization']}, {'name': 'Physics-Constrained ML and Thermodynamic Consistency', 'level': 'Advanced', 'description': 'Techniques for embedding physical laws and conservation principles directly into neural network architectures.', 'key_subtopics': ['Soft Constraints via Multi-objective Loss Functions', 'Hard Constraints through Projection Layers and Null-space Methods', 'Thermodynamic Preservation (Energy, Momentum, Mass)', 'Lagrangian vs. Eulerian ML Formulations', 'Hamiltonian Neural Networks for Conservative Systems', 'Differentiable Boundary Conditions']}, {'name': 'Hybrid Modeling and ML-based Subgrid-Scale Parameterization', 'level': 'Frontier', 'description': 'Replacing or enhancing conventional physics schemes (clouds, convection) with high-fidelity machine learning emulators.', 'key_subtopics': ['Convective Parameterization using Deep Neural Networks', 'Online Stability and Coupled Model Drift Analysis', 'Multi-fidelity Learning from Cloud-Resolving Models (CRM)', 'Active Learning for Adaptive Parameterization', 'Interpreting ML-based Emulators for Physical Insight', 'Hybrid ML-PDE Solvers and Time-stepping Stability']}, {'name': 'Earth System Foundation Models and Multi-Modal SSL', 'level': 'Frontier', 'description': 'Designing large-scale pre-trained models that leverage diverse satellite, station, and simulation data.', 'key_subtopics': ['Masked Autoencoders (MAE) for Satellite Imagery', 'Vision Transformers (ViT) for Global Atmospheric State', 'Self-Supervised Learning (SSL) on Reanalysis Data (ERA5)', 'Cross-Modal Alignment (Radar, Lidar, and Numerical Fields)', 'Scaling Laws in Earth System Modeling', 'Few-shot Transfer Learning for Regional Climate Impacts']}, {'name': 'Causal Inference for Climate Teleconnections and Attribution', 'level': 'Frontier', 'description': 'Utilizing causal discovery algorithms to identify drivers of extreme events and long-range climate dependencies.', 'key_subtopics': ['Constraint-based Causal Discovery (PC and FCI Algorithms)', 'Granger Causality in Spatiotemporal Time-Series', 'Structural Causal Models (SCM) for Extreme Event Attribution', 'Counterfactual Reasoning in Climate Change Scenarios', 'Causal Effect Estimation under Selection Bias', 'Discovering Teleconnection Patterns via Causal Networks']}], 'status': 'success'}
{'discipline': 'Lexical Semantics and Word Sense Disambiguation', 'subfield': 'Linguistic Foundations', 'field': 'Natural Language Processing', 'subjects': [{'name': 'Formal Lexical Semantics and Relational Structures', 'level': 'Foundational', 'description': "Exploration of the structuralist and generative perspectives on how word meanings are organized and related within a language's lexicon.", 'key_subtopics': ["Pustejovsky's Generative Lexicon Theory and Qualia Structure", 'Lexical Relations: Hyponymy, Meronymy, Troponymy, and Antonymy', 'Componential Analysis and Semantic Features', 'Truth-Conditional Semantics and Lexical Entailment', 'Fillmore’s Case Grammar and Frame Semantics', 'The Lexicalization of Events and Aspectual Classes (Aktionsart)']}, {'name': 'Distributional Semantics and Algebraic Vector Spaces', 'level': 'Foundational', 'description': 'Mathematical foundations of the Distributional Hypothesis and the transition from sparse co-occurrence matrices to dense embeddings.', 'key_subtopics': ['Pointwise Mutual Information (PMI) and Positive PMI (PPMI)', 'Latent Semantic Analysis (LSA) and Singular Value Decomposition (SVD)', 'Static Word Embeddings: Skip-gram, CBOW, and GloVe', 'Hyperbolic Embeddings for Hierarchical Lexical Taxonomy', 'The Hubness Problem in High-Dimensional Vector Spaces', 'Evaluation Metrics: Word Similarity Tasks and TOEFL Synonymy Tests']}, {'name': 'Knowledge-Based Word Sense Disambiguation and Graph Algorithms', 'level': 'Advanced', 'description': 'Deep dive into algorithms that leverage structured lexical resources like WordNet and BabelNet to resolve ambiguity.', 'key_subtopics': ['The Lesk Algorithm and its variations (Simplified, Extended)', 'Graph-based Centrality Measures: Personalized PageRank (PPR) for WSD', 'Semantic Relatedness Measures: Path-based, Information Content, and Gloss-based', 'Knowledge Graph Embeddings for Lexical Nodes (TransE, RotatE)', 'BabelNet and Multilingual Semantic Network Construction', 'Random Walks on Lexical-Semantic Graphs']}, {'name': 'Contextualized Representations and Neural WSD Architectures', 'level': 'Advanced', 'description': 'Focus on the shift toward deep transformer-based models and the representation of word senses as dynamic contextual vectors.', 'key_subtopics': ['Bi-Encoder and Cross-Encoder Architectures for Gloss-Based WSD', 'Sense-Aware Attention Mechanisms and Attention Probing', 'Nearest Neighbor (k-NN) Classification in Embedding Space (1NN-WSD)', 'Fine-tuning BERT and RoBERTa for Sequence Labeling vs. Classification', 'Sense Vocabulary Compression and Canonical Sense Representations', 'Disambiguation-Specific Pre-training Objectives']}, {'name': 'Cross-Lingual Lexical Semantics and Multilingual Transfer', 'level': 'Advanced', 'description': 'Investigation of how word senses are mapped across languages and the utilization of multilingual models for low-resource disambiguation.', 'key_subtopics': ['Cross-lingual Word Embedding Alignment (Procrustes Analysis)', 'Zero-Shot Cross-lingual Transfer for WSD', 'Universal Dependencies and Cross-lingual Semantic Role Labeling', 'Translation-based Disambiguation and Parallel Corpora Projection', 'Multilingual BERT (mBERT) and XLM-R in Lexical Tasks', 'Inter-lingual Linked Data (ILLD) and the Semantic Web']}, {'name': 'Compositional Lexical Semantics and Thematic Fit Modeling', 'level': 'Frontier', 'description': 'Analysis of how word meanings combine into larger units and the disambiguation of words through their syntactic-semantic context.', 'key_subtopics': ['Mathematical Models of Compositionality: Additive, Multiplicative, and Tensor Products', 'Selectional Preference Induction and Thematic Fit', 'Predicate-Argument Structure and Verb Polysemy', 'Co-composition and Coercion in the Generative Lexicon', 'Multi-word Expression (MWE) Identification and Idiom Disambiguation', 'Noun-Noun Compound Interpretation and Semantic Relations']}, {'name': 'Neuro-Symbolic Integration for Lexical Inference', 'level': 'Frontier', 'description': 'Research into hybrid systems that combine the reasoning capabilities of Large Language Models with the precision of symbolic ontologies.', 'key_subtopics': ['Knowledge-Augmented Language Models (K-BERT, KEPLER)', 'Differentiable Reasoning over Formal Ontologies', 'Injecting Relational Constraints into Neural Loss Functions', 'Constrained Decoding for Sense Tagging with LLMs', 'Combining Probabilistic Logic with Neural Embeddings', 'Ontology-Driven Data Augmentation for Rare Senses']}, {'name': 'Open-World WSD and Few-Shot Lexical Learning', 'level': 'Frontier', 'description': 'Addressing the challenges of long-tail sense distributions, novel sense discovery, and data scarcity in word sense disambiguation.', 'key_subtopics': ['Zero-Shot and Few-Shot Learning for Under-Represented Senses', 'Novel Sense Detection and Out-of-Vocabulary (OOV) Handling', 'In-Context Learning and Prompt Engineering for WSD in LLMs', 'Chain-of-Thought Reasoning for Disambiguating Complex Polysemy', 'Continual Learning for Evolving Lexicons and Neologisms', 'Active Learning Strategies for Efficient Sense Annotation']}], 'status': 'success'}
{'discipline': 'Variational Inequalities and Game-theoretic Optimization', 'subfield': 'Optimization Theory', 'field': 'Mathematical Foundations of AI', 'subjects': [{'name': 'Operator Theory and the Geometry of Variational Inequalities', 'level': 'Foundational', 'description': 'Fundamental mathematical framework for monotone operators and existence theory in Hilbert and Banach spaces.', 'key_subtopics': ["Maximal Monotone Operators and Minty's Theorem", 'Stampacchia and Hartman-Stampacchia Inequalities', 'Resolvents and Cayley Transforms', 'KKM (Knaster-Kuratowski-Mazurkiewicz) Theory', 'Projection Mappings and Non-expansive Operators', 'Variational Analysis of Proximal Mappings', 'Fitzpatrick Functions and Representative Functions']}, {'name': 'First-Order Splitting Methods and Proximal Algorithms', 'level': 'Foundational', 'description': 'Core algorithmic structures for solving decomposed optimization problems and variational inclusions.', 'key_subtopics': ['Forward-Backward Splitting (FBS) and Iterative Soft-Thresholding', 'Douglas-Rachford and Peaceman-Rachford Splitting', 'Mirror Prox and Bregman Divergence Methods', 'Extragradient (EG) Methods for Saddle Point Problems', 'Primal-Dual Hybrid Gradient (PDHG) / Chambolle-Pock Algorithm', 'Accelerated Proximal Point Algorithms', 'Inexact Proximal Methods and Error Criteria']}, {'name': 'Stochastic and Variance-Reduced Variational Inequalities', 'level': 'Advanced', 'description': 'Adaptation of VI solvers to the high-noise, large-scale data regimes prevalent in modern AI.', 'key_subtopics': ['Stochastic Approximation and Robbins-Monro Procedures', 'Variance Reduction for Games (SVRG-VI, SAGA-VI)', 'Stochastic Mirror Prox and Dual Averaging', 'Lower Bounds for Stochastic Variational Inequalities', 'Adaptive Stepsize Rules (AdaGrad/Adam) in Game Dynamics', 'Variance-Reduced Extragradient and OGDA', 'Noise-Robustness and Biased Gradient Estimates']}, {'name': 'Non-Cooperative Game Dynamics and Saddle Point Problems', 'level': 'Advanced', 'description': 'Analysis of convergence behavior and stability in minimax optimization and multi-agent systems.', 'key_subtopics': ['Nash Equilibrium vs. Local Stackelberg Equilibrium', 'Last-Iterate Convergence vs. Average-Iterate Convergence', 'Optimistic Gradient Descent Ascent (OGDA)', 'Rotation Dynamics and Limit Cycles in GANs', 'Hamiltonian Gradient Methods for Game Stabilization', 'Symplectic Gradient Adjustment (SGA)', 'Coherent and Correlated Equilibria in Large-Scale Games']}, {'name': 'Non-Monotone Variational Inequalities and Local Stability', 'level': 'Frontier', 'description': 'Extending the reach of VI theory to non-convex-non-concave landscapes and non-monotone operators.', 'key_subtopics': ['Co-monotonicity and Weak Monotonicity Conditions', 'Variational Inequalities with Polyak-Lojasiewicz (PL) Geometry', 'Minty Solutions vs. Stampacchia Solutions in Non-Monotone Settings', 'Escaping Limit Cycles and Spurious Equilibria', 'The Potential-Interaction Decomposition of Vector Fields', 'Global Convergence via Star-Convexity and M-Natural Monotonicity']}, {'name': 'Mean Field Games and Infinite-Dimensional Optimization', 'level': 'Frontier', 'description': 'The intersection of optimal transport, stochastic control, and game theory for continuum populations.', 'key_subtopics': ['McKean-Vlasov Stochastic Differential Equations', 'Master Equations in Mean Field Games', 'Langevin Dynamics for Sampling and VI', 'Entropic Regularization of Mean Field Equilibria', 'Sinkhorn Divergences in Game-Theoretic Contexts', 'Particle Approximations and Propagation of Chaos', 'Neural Mean Field Games for Population Modeling']}, {'name': 'Distributed and Federated Variational Inequalities', 'level': 'Frontier', 'description': 'Solving VIs over decentralized networks with constraints on communication and data privacy.', 'key_subtopics': ['Consensus-Based Variational Inequalities', 'Communication-Efficient Quantization for VIs', 'Asynchronous Mirror Prox and Delay Robustness', 'Byzantine-Resilient Multi-Agent Optimization', 'Heterogeneous Data Distributions (Non-IID) in Federated VI', 'Local-Update Extragradient Algorithms', 'Privacy-Preserving Mechanism Design for Game Solvers']}, {'name': 'Continuous-Time Dynamics and ODE Representations', 'level': 'Frontier', 'description': 'Theoretical analysis of optimization through the lens of dynamical systems and differential geometry.', 'key_subtopics': ['High-Resolution ODEs for Accelerated Methods', 'Lyapunov Stability Analysis of Game Dynamics', 'Symplectic Integrators and Geometric Numerical Integration', 'Dissipative Systems and Passivity Theory in VI', 'Control-Theoretic Perspectives on Optimization Momentum', 'Differential Game Theory and Hamilton-Jacobi-Isaacs Equations', 'Attractors and Bifurcation Theory in Multi-Agent Learning']}], 'status': 'success'}

In [6]:
# convert to dataframe
import pandas as pd

data = []
with jsonlines.open('../data/prompts/taxonomy_phase2_gemini-3-flash-preview.jsonl') as reader:
    for obj in reader:
        data.append(obj)

df = pd.DataFrame(data)

In [9]:
type(df["subjects"])

pandas.Series

In [11]:
import json

def filter_taxonomy(input_path, output_path):
    processed_lines = 0
    kept_subjects = 0
    removed_subjects = 0

    with open(input_path, 'r', encoding='utf-8') as infile, \
         open(output_path, 'w', encoding='utf-8') as outfile:
        
        for line in infile:
            if not line.strip():
                continue
                
            try:
                data = json.loads(line)
                
                # Sprawdzamy czy linijka zawiera klucz 'subjects'
                if 'subjects' in data:
                    original_len = len(data['subjects'])
                    
                    # Zostawiamy tylko te, które NIE są "Foundational"
                    filtered_subjects = [
                        subject for subject in data['subjects'] 
                        if subject.get('level') != 'Foundational'
                    ]
                    
                    # Aktualizujemy listę w oryginalnym słowniku
                    data['subjects'] = filtered_subjects
                    
                    # Zliczanie statystyk
                    kept_subjects += len(filtered_subjects)
                    removed_subjects += (original_len - len(filtered_subjects))
                    
                    # Zapisujemy linijkę tylko, jeśli po filtrowaniu został jakikolwiek subject
                    if len(filtered_subjects) > 0:
                        json.dump(data, outfile, ensure_ascii=False)
                        outfile.write('\n')
                        processed_lines += 1
                        
            except json.JSONDecodeError as e:
                print(f"Błąd parsowania JSON w linijce: {e}")

    print("Zakończono filtrowanie!")
    print(f"Zapisane linie JSONL: {processed_lines}")
    print(f"Pozostawione (Advanced/Frontier) tematy: {kept_subjects}")
    print(f"Usunięte (Foundational) tematy: {removed_subjects}")

In [13]:
input_filename = '../data/prompts/taxonomy_phase2_gemini-3-flash-preview.jsonl'
output_filename = '../data/prompts/taxonomy_phase2_gemini-3-flash-preview_adv.jsonl'

filter_taxonomy(input_filename, output_filename)

Zakończono filtrowanie!
Zapisane linie JSONL: 653
Pozostawione (Advanced/Frontier) tematy: 4024
Usunięte (Foundational) tematy: 1200

In [1]:
# open pkl as dataframe
import pandas as pd
df = pd.read_pickle('../data/retrieval/retrieved_contexts.pkl')
print(df.head())

   prompt_id                                           topic_id  \
0          0  Probabilistic Information Retrieval and BM25 V...
1          1  Hierarchical Decomposition and Temporal Abstra...
2          2  Theoretical Interpretability and Representatio...
3          3  Masked Auto-Encoding as Generative Predictive ...
4          4  Multilingual Vector Space Alignment and Manifo...

                                   retrieved_context  \
0  For a query $Q$ and a passage $P$, BM25 is com...
1  ABSTRACT\nThe ability to discover useful behav...
2  2. We further consider two subsets of IN1K con...
3  **Probabilistic or generative modeling.** Simi...
4  6. Word-Level Alignment Models\n\nIn the follo...

                                        context_meta
0  [{'chunk_id': 4, 'doc_id': '196e1b5ee392199044...
1  [{'chunk_id': 0, 'doc_id': 'a7934cf662959e4526...
2  [{'chunk_id': 3, 'doc_id': '5aaef3b0a614f7f2b2...
3  [{'chunk_id': 10, 'doc_id': 'b1fc7d96d732f9951...
4  [{'chunk_id': 8, 'doc_id': '46c112747fb44f82d3...

In [7]:
df.iloc[89]["context_meta"]

[{'chunk_id': 0, 'doc_id': 'c8dd6a52a2451cb7d0fb92961525b298c6ba1755'},
 {'chunk_id': 1, 'doc_id': 'c8dd6a52a2451cb7d0fb92961525b298c6ba1755'},
 {'chunk_id': 9, 'doc_id': 'c8dd6a52a2451cb7d0fb92961525b298c6ba1755'},
 {'chunk_id': 8, 'doc_id': 'c8dd6a52a2451cb7d0fb92961525b298c6ba1755'},
 {'chunk_id': 4, 'doc_id': 'c8dd6a52a2451cb7d0fb92961525b298c6ba1755'},
 {'chunk_id': 17, 'doc_id': 'b5b98051b65da6b1b3b579862b0407d48c5bef48'},
 {'chunk_id': 10, 'doc_id': 'c8dd6a52a2451cb7d0fb92961525b298c6ba1755'},
 {'chunk_id': 7, 'doc_id': 'c8dd6a52a2451cb7d0fb92961525b298c6ba1755'},
 {'chunk_id': 2, 'doc_id': '55ad60edf95db25bc76001f38ffcb3131c7dded0'},
 {'chunk_id': 6, 'doc_id': 'ba114923ff55abaca136fa64ad097d68971652e1'}]

In [2]:
import pandas as pd

df = pd.read_csv('../data/datasets/synthetic_sft_dataset.csv')
df.head()

,prompt_id,user_query,raw_context,retriever_reasoning,retriever_extracted_info,generator_is_answerable,generator_reasoning,generator_hypothesis,generator_falsification
0,423,Evaluate the efficacy of integrating dependent...,ABSTRACT\nThis paper analyzes the vulnerabilit...,The research query asks to evaluate the effica...,Key Variables:\n- Trusted Execution Environmen...,False,The provided information is insufficient to fo...,A hypothesis cannot be formulated as the extra...,Falsification criteria cannot be defined as no...
1,467,Compare the robustness and adaptation efficien...,ABSTRACT\nWe introduce an approach to multilin...,The research query asks for a comparison of ad...,## Comparison of Adversarial Domain Adaptation...,True,1. The provided information directly compares ...,If a polyglot TTS system utilizes a meta-learn...,The hypothesis would be falsified if a TTS mod...
2,424,What are the theoretical and practical limitat...,$L$-fold symmetric structure does not change w...,The context provides several theoretical and p...,Key Variables:\n- Lie group equivariant neural...,True,1. The provided information establishes a dire...,If the order `L` of spherical harmonics and th...,The hypothesis would be falsified if an experi...
3,466,Evaluate the trade-offs between computational ...,Dynamic pricing as a bandit problem has been i...,The research query asks for an evaluation of t...,Key Variables:\n- **N**: Number of independe...,True,The provided information establishes that both...,If a dynamic pricing strategy is derived using...,"In a comparative study using an identical, sca..."
4,422,Investigate the necessary and sufficient condi...,ABSTRACT\nAdaptive optimization methods are we...,The research query asks for necessary and suff...,Key Variables/Concepts:\n- Loss landscape geom...,True,The provided information establishes a clear c...,If the network width is sufficiently increased...,"The hypothesis would be falsified if, for a ne..."

In [10]:
df_answerable = df[df['generator_is_answerable'] == True]
df_answerable.head()

,prompt_id,user_query,raw_context,retriever_reasoning,retriever_extracted_info,generator_is_answerable,generator_reasoning,generator_hypothesis,generator_falsification
1,467,Compare the robustness and adaptation efficien...,ABSTRACT\nWe introduce an approach to multilin...,The research query asks for a comparison of ad...,## Comparison of Adversarial Domain Adaptation...,True,1. The provided information directly compares ...,If a polyglot TTS system utilizes a meta-learn...,The hypothesis would be falsified if a TTS mod...
2,424,What are the theoretical and practical limitat...,$L$-fold symmetric structure does not change w...,The context provides several theoretical and p...,Key Variables:\n- Lie group equivariant neural...,True,1. The provided information establishes a dire...,If the order `L` of spherical harmonics and th...,The hypothesis would be falsified if an experi...
3,466,Evaluate the trade-offs between computational ...,Dynamic pricing as a bandit problem has been i...,The research query asks for an evaluation of t...,Key Variables:\n- **N**: Number of independe...,True,The provided information establishes that both...,If a dynamic pricing strategy is derived using...,"In a comparative study using an identical, sca..."
4,422,Investigate the necessary and sufficient condi...,ABSTRACT\nAdaptive optimization methods are we...,The research query asks for necessary and suff...,Key Variables/Concepts:\n- Loss landscape geom...,True,The provided information establishes a clear c...,If the network width is sufficiently increased...,"The hypothesis would be falsified if, for a ne..."
5,468,Given the sensitivity of end-to-end neural tra...,We also observe from Fig. 2 that the best perf...,The research query asks for meta-learning stra...,Key Variables:\n- Channel State Information (C...,True,1. The provided information establishes a key ...,If a DeepJSCC architecture is augmented with a...,The hypothesis would be falsified if a DeepJSC...